name: ci
on: [push, pull_request]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v1

      - name: Install dependencies 📦
        uses: cypress-io/github-action@v1
        with:
          runTests: false

      - name: Build 🏗
        run: npm run build

      - name: ng7 example 💎
        uses: cypress-io/github-action@v1
        with:
          working-directory: examples/ng7

      - name: ng9 example 💎
        uses: cypress-io/github-action@v1
        with:
          working-directory: examples/ng9

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
